### ISSUE TITLE
Maintain a dictionary file of metrics and historical names

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#101]
For any new metric, add the name and definition to a metrics.dictionary.md file. **include any historical names that were renamed**

**Comment by klumb** [comment]
I think we need to collect some basic terminology to start.

**Comment by sgoggins** [comment]
Lets make it simply changes from here forward.

**Comment by klumb** [comment]
add proposals and reviews

**Comment by jgbarah** [comment]
I've added it as a part of #119, following the suggestion by @sgoggins.

**Comment by harshalmittal4** [comment]
@jgbarah, @sgoggins, @klumb 
if there is anything else that needs to be added to name_changes.md (not sure whether to add the names of the existing metrics), let me know and I'll update it there.

**Comment by jgbarah** [comment]
I think we can close this now, after merging #119 which includes a first version of that dictionary.
