### ISSUE TITLE
[metrics] "Reviews" instead of "Proposals"?

### ISSUE THREAD

**Issue by jgbarah** [chaoss/wg-evolution#110]
Some people have pointed out that the name "Proposals" is difficult to map to pull requests, merge requests or code reviews, and that "proposals" is not used in this context.

Proposals came from "proposals of changes to the code", but I agree that the word "proposals", isolated, is difficult to map to a code review process. It is the name we're currently used in the code development focus area (file [code_development.md](https://github.com/chaoss/wg-gmd/blob/master/focus_areas/code_development.md)).

Thus, I propose to change "Proposals" for "Reviews", which would be much more explicit, and would still include pull requests in the case of GitHub, merge requests in the case of GitLab, and code reviews in the case of Gerrit.

The change would be in all metrics names, such as "Proposals" -> "Reviews", or "Proposals_Accepted" -> "Reviews_Accepted".

If nobody opposes, I will produce the pull request for that (or anyone who has some time could do it ,-) ).

Any feedback is welcome!!

**Comment by germonprez** [comment]
This makes sense to me. I didn't even understand 'proposals' until you explained it here. Reviews is something I understand more :)

**Comment by rsanchez-seerene** [comment]
Very important concept, which reminds me the document control system and RFC processes: Submit fro review, Pending review, Pending approval, release, obsoleted. However in this case the author can decline review comments/suggestions.   
![ReviewProcess](https://user-images.githubusercontent.com/19904348/54718873-d2aa6400-4b5b-11e9-9f9c-e702bfe5f404.png)

**Comment by germonprez** [comment]
So it seems like the inclination is for 'review'

**Comment by jgbarah** [comment]
Good. Thanks for the feedback. If there is no comments against, I will produce the pr changing this.

**Comment by sgoggins** [comment]
Pull_Merge_Request? 
Forked_code_merge_request?
I think the word "review" is confusing with regards to code reviews.

**Comment by jgbarah** [comment]
Thanks for the feedback, @sgoggins. My comments on it:

* Pull_Merge_Request: a bit longish, but also misses important systems, such as Gerrit, where the name has nothing to do with "pull request" or "merge request".
* Forked_code_merge_request: not sure what "forked code" means in this context...

But, from a general point of view, why "review" is confusing when talking about code *reviews*? Maybe "Code_Review" would be more clear?

**Comment by jgbarah** [comment]
Any other comment about this?

**Comment by sgoggins** [comment]
what about "code_integration"?

**Comment by germonprez** [comment]
As related now to #119
