### ISSUE TITLE
Deciding a new name for this working group

### ISSUE THREAD

**Issue by jgbarah** [chaoss/wg-evolution#124]
After [some discussion in the mailing list](https://lists.linuxfoundation.org/pipermail/chaoss/2019-March/000401.html), it seems we have a consensus on changing the name of the working group to make it more easy to understand to newcomers.

Proposals that could get consensus are, for now: Activity, Lifecycle, and Evolution.

Which one do you prefer? (or better, rank them in order, so that we can know about all preferences). And of course, if you want to explain some rationale, beyond what was already discussed in the mailing list, please do.

**Comment by rsanchez-seerene** [comment]
After reading some literature on the subject (Thank you Tom) I can understand the context of Software Evolution as the encompassing name with finite development periods/activity/processes that have a Lifecycle.

**Comment by GeorgLink** [comment]
- evolution
- lifecycle
- (activity)

**Comment by foundjem** [comment]
1. Evolution 
2. Activity
3. Lifecycle

**Comment by sgoggins** [comment]
Evolution.

**Comment by jgbarah** [comment]
We decided the change in name during the latest meeting, based on the feedback here: Evolution. After a reasonable time seeing that nobody opposed, i changed the name of the repository, and accepted a patch changing the README.md file.

Thanks to all of you who participated!
