### ISSUE TITLE
[metrics] Metric files are missing

### ISSUE THREAD

**Issue by vchrombie** [chaoss/wg-evolution#140]
It seems that many metric description files are missing in the [wg-gmd/metrics](https://github.com/chaoss/wg-gmd/tree/master/metrics) folder. Few are not created, few have broken links. 

If you are still discussing and working on the metric, then you can close this issue. But, if it is like a mistake, I can send a PR fixing it. :slightly_smiling_face:

**Comment by vchrombie** [comment]
@jgbarah @sgoggins 
I will be asking about the files here. You can decide what to do about such files and lets see what we can do it. :smiley:

**Comment by vchrombie** [comment]
These metrics in the focus_areas doesn't have a `.md` file in metrics (not even the template)

- [Pull Request Merged](https://github.com/chaoss/wg-gmd/blob/master/metrics/pull-requests-merged.md)
- [Pull Requests Closed](https://github.com/chaoss/wg-gmd/blob/master/metrics/pull-requests-closed.md)
- [Pull Requests Code Review](https://github.com/chaoss/wg-gmd/blob/master/metrics/pull-requests-code-reviews.md)
- [New Contributors of Initiated Code Reviews]
- [Open Issues](https://github.com/chaoss/wg-gmd/blob/master/metrics/issues-open.md)

If you are planning to create them later maybe during the GSoC period, I am ok with it. You can use this issue as a reference at that time but if you are likely to close this asap then I would like to send a PR to this issue.

**Comment by vchrombie** [comment]
I doubt the below metrics have a file but the link is broken. I have corrected the link beside it 

| Metric with broken link | Correct link |
| --- | --- |
| [Lines of Code Changed]() | https://github.com/chaoss/wg-gmd/blob/master/metrics/code-lines-of-code-changed.md |
| [New Contributors of Initiated Code Reviews]() | https://github.com/chaoss/wg-gmd/blob/master/metrics/pull-requests-code-reviews-contributors-new.md |
| [Closed Issues](https://github.com/chaoss/wg-gmd/blob/master/metrics/issues-closed.md) | https://github.com/chaoss/wg-gmd/blob/master/metrics/Issues_Closed.md |

Please correct me if I am wrong.

**Comment by vchrombie** [comment]
The below files look the same, I would like to learn if there is any under depth meaning of this as I see @jgbarah comment over there

> What is the number of persons contributing with reviews of code for the first time? this is currently the same as pull-request-code-reviews-new

- [pull-requests-code-reviews-contributors-new.md](https://github.com/chaoss/wg-gmd/blob/master/metrics/pull-requests-code-reviews-contributors-new.md), [pull-request-code-reviews-new.md](https://github.com/chaoss/wg-gmd/blob/master/metrics/pull-request-code-reviews-new.md)

**Comment by harshalmittal4** [comment]
Hey @vchrombie, as you know this project is still under development, and so the files would be made in place once the implementation for those metrics is also done. Till then I don't think adding metric files by including only the headers will do any good. Also considering the fact that this is the case for only a few metrics :slightly_smiling_face:
Anyways, this was just my opinion.

**Comment by vchrombie** [comment]
Ok, @harshalmittal4. Thanks for the comment.

> If you are still discussing and working on the metric, then you can close this issue. But, if it is like a mistake, I can send a PR fixing it.

I too felt the same, maybe we can use this issue as a reference at that time.

If you anyone feels this as unnecessary, please let me know. I am ok with closing this issue.

**Comment by harshalmittal4** [comment]
>I too felt the same, maybe we can use this issue as a reference at that time.

Agreed! :innocent:

**Comment by vchrombie** [comment]
@jgbarah @sgoggins 
any comments on this issue?

**Comment by jgbarah** [comment]
I would just let this as it is now, if needed explaining in the README.md file that we're still in the process of producing metrics, which means that many of the metrics found in focus area files are still not detailed, and don't have their own file.

Do you think you could produce such a text for the README.md file?

I'm labeling this as help wanted, just in case someone wants to produce that pr.

(And of course, thanks a lot for raising this issue)

**Comment by vchrombie** [comment]
> I would just let this as it is now, if needed explaining in the README.md file that we're still in the process of producing metrics, which means that many of the metrics found in focus area files are still not detailed, and don't have their own file.
> 
> Do you think you could produce such a text for the README.md file?

It would be good, I can produce a PR if you are Ok with that.

**Comment by jgbarah** [comment]
> It would be good, I can produce a PR if you are Ok with that.

Yes, please, go ahead.

**Comment by sgoggins** [comment]
I agree that we should simply make a note in the README.md that metrics without full definitions are great places for newcomers to start, and that we are leaving them initially with a template so that newcomers will have the structure "at the ready" and be able to structure the definition as we intend. 

I think we might also consder opening issues for each metric that is empty

**Comment by vchrombie** [comment]
Sorry, I couldn't attend the meeting. I went through the discussion in the minutes just now. I will produce the required PR.

**Comment by vchrombie** [comment]
> I think we might also consder opening issues for each metric that is empty

Maybe we can do this while the GSoC coding time. We can open one issue for each metric for discussion, clarifications of doubts on the implementation of the metrics.

**Comment by jgbarah** [comment]
I just merged the PR. I guess we can close this issue, right?
