### ISSUE TITLE
Naming and a few 404 errors

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-evolution#149]
Just going through the repository and there are a few instances of 404s for some of the metrics detail pages and the naming is also not consistent between the names on the focus area and the detail page. I suggest that at the next Evolution meeting, we spend some time just walking through each focus area metric to resolve any inconsistencies.

**Comment by jgbarah** [comment]
Some time ago we decided to work in the focus area file, and move the names of the metrics to the "new" naming when they were linked from it. Anyway, most of the "wrong" metrics are empty templates, so we could revisit this decision and get rid of them, if we consider that's better.

**Comment by germonprez** [comment]
Complete
