### ISSUE TITLE
[GSoC] Create implementations for a few more metrics

### ISSUE THREAD

**Issue by Polaris000** [chaoss/wg-evolution#157]
After finishing the Code_changes-git metric reference implementation, my goal is to finish a few more this week. The metrics to be worked on will most likely be all other commit related metrics.

**Comment by jgbarah** [comment]
Please, have a look at #177, still under review. In it, I restructure your code for the first metric. Still some restructuring is needed, but maybe you can get the idea. If so, please consider re-writing these other metrics with that structure in mind (I think it is not far away from your proposal, but trying to formalize the structure a bit).
