### ISSUE TITLE
[sigils] Document how GrimoireLab dashboards can display released metrics

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-evolution#159]
This issue proposes to include in the known implementation sections of metrics a description of how GrimoireLab provides these metrics. 

This requires updates to GrimoreLab Sigils dashboard description to align them with the CHAOSS metric definition.

**Comment by jgbarah** [comment]
Good idea, @GeorgLink !!

Some pointers, just in case:

* [Example of a dashboard description in Sigils for a CHAOSS metric](https://chaoss.github.io/grimoirelab-sigils/chaoss-gmd-cde/lines_of_code_changed/). Maybe it would be good enough to write these kind of descriptions in Sigils, and link from the metrics description, or you think it is better to include a part of this content in the metrics description itself?

* [Live dashboard including the above metric, in the CHAOSS dashboard](https://chaoss.biterg.io/app/kibana#/dashboard/f13af0e0-18e5-11e9-ba47-d5cbef43f8d3)

* [Description page in Sigils](https://github.com/chaoss/grimoirelab-sigils/blob/master/docs/_chaoss-gmd-cde/lines_of_code_changed.md) for the same metric. The description in the dashboard, linked above, comes from this file.

**Comment by GeorgLink** [comment]
Thanks @jgbarah. I don't know what the best format is. 
@alpgarcia and I will explore this together on Tuesday. 
We want to have a first draft (pull request) ready to discuss at the next Evolution WG meeting.

**Comment by jgbarah** [comment]
I think we're done with this. Thanks!
