### ISSUE TITLE
Metrics for V1 Release

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-evolution#165]
Hi, 

It's looking like the following Code Development metrics are (nearly?) ready for release: 

Code_Changes
Code_Changes_Lines
Issues_New
Issues_Active
Issues_Closed
Reviews
Reviews_Accepted
Reviews_Declined

@jgbarah @sgoggins @GeorgLink If you have any finishing touches that need to be done before June 21, that would be great :)

**Comment by jgbarah** [comment]
Thanks, Matt. I hope we can review all of this in our weekly meeting. There are some other metric in progress in a pull request, and some improvements as well.

**Comment by foundjem** [comment]
Looks good to me, just a clarification on the "Review" metric, do we keep track of the number of iteration a Refiew undergoes?

**Comment by jgbarah** [comment]
> Looks good to me, just a clarification on the "Review" metric, do we keep track of the number of iteration a Refiew undergoes?

Not in the "basic" Review metric. But that's a good diea, and an interesting metric that we could have for goal "Efficiency". Please, feel free to comment that in #138, and/or produce a pull request on the [code development focus area](https://github.com/chaoss/wg-evolution/blob/master/focus_areas/code_development.md).

**Comment by jgbarah** [comment]
WRT the metrics ready for release, the proposal we agreed during our meeting today, following the idea of accepting all metrics that went through code review, is to propose all metrics in the ["Summary or Metrics"](https://github.com/chaoss/wg-evolution/blob/master/focus_areas/code_development.md#summary-of-metrics) table:


Goal | Question | Metric
-- | -- | --
Activity | Changes | Code_Changes
Activity | Changes | Code_Changes_Lines
Activity | Issues | Issues_New
Activity | Issues | Issues_Active
Activity | Issues | Issues_Closed
Activity | Reviews | Reviews
Activity | Reviews | Reviews_Accepted
Activity | Reviews | Reviews_Declined
Efficiency | Reviews | Reviews_Duration

If nobody objects, this wiill be the list of metrics released in V1.

**Comment by germonprez** [comment]
This sounds great to me. Thanks for the push on this.

**Comment by GeorgLink** [comment]
Yes. Thank you.
