### ISSUE TITLE
Candidate Release Comments (Code Changes)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-evolution#181]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Code Changes**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Code_Changes.md

Release candidate: https://chaoss.community/metric-code-changes/

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by klumb** [comment]
Broken link at line 104 (See reference implementation for git ) - Might be a dead link

**Comment by Polaris000** [comment]
@GeorgLink, the implementations have been redesigned. The link to the notebook for Code_Changes-Git is this:   
https://github.com/chaoss/wg-evolution/blob/master/implementations/notebooks_df/code_changes_git.ipynb

**Comment by jgbarah** [comment]
Yes, the link should go to the new implementation (see @Polaris000 comment)

**Comment by foundjem** [comment]
The rationale for `Naive implementation` is reasonable enough, but its not clear to me if "affecting the code" means introducing a bug for example. If that should be the case here, then maybe SZZ algorithm will best tell us which particular commit introduce a bug. What do you think?

**Comment by jgbarah** [comment]
In this case, "affecting the code" means that the change touches "source code" or if you want, "source code files". It may introduce a bug, or not, that is something which is not addressed here: only the change is relevant. Think of a commit that may include source code files between the files it changes, or not.

Is it more clear now? Do you think we should clarify the text?

**Comment by foundjem** [comment]
@jgbarah thanks, it's clearer now. Since we are not considering if multiple changes might be bugged prone.

**Comment by rpaik** [comment]
For the "Activity", suggest rephrasing this to "Learn about activity involved in developing (e.g. adding/changing) code.

**Comment by rpaik** [comment]
Rephrase the third question to "How many issues related to the source code are there during a certain time period?"

**Comment by jgbarah** [comment]
Thanks for your comments, @rpaik. I understand that you refer to the focus area document, not to this specific metric. I've just opened #209 with (hopefully) your proposal.

**Comment by germonprez** [comment]
Resolved
