### ISSUE TITLE
Candidate Release Comments (Code Changes Lines)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-evolution#182]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Code Changes Lines**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Code_Changes_Lines.md

Release candidate: https://chaoss.community/metric-code-changes-lines

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by sgoggins** [comment]
I think we should provide a reference for different types of merge commits and how they might be evaluated. I don't think its complex, but different systems use different types of flags (i.e., Github v a straightup git repo v gitlab).

**Comment by sgoggins** [comment]
I would like to see: 
1. Lines Deleted
2. Lines added
3. Whitespace 

as lines of code categories that are optional.

**Comment by jgbarah** [comment]
> I think we should provide a reference for different types of merge commits and how they might be evaluated. I don't think its complex, but different systems use different types of flags (i.e., Github v a straightup git repo v gitlab).

Thanks, @sgoggins. Changes in source code refer mostly to commits, and thus are the same with independence of how commits are reviewed. In the metric description we have a [specific section on git](https://github.com/chaoss/wg-evolution/blob/master/metrics/Code_Changes_Lines.md#specific-description-git), because currently, this is defined only for git commits. But of course, other source code review systems could be considered.

**Comment by jgbarah** [comment]
> I would like to see:
> 
>     1. Lines Deleted
> 
>     2. Lines added
> 
>     3. Whitespace
> 
> 
> as lines of code categories that are optional.

Thanks, @sgoggins. What do you mean by "categories that are optional"?

**Comment by foundjem** [comment]
@sgoggins I think we can know this from git log/diff?

The visualization makes this metric more informative.

**Comment by germonprez** [comment]
Resolved via: 
https://github.com/chaoss/wg-evolution/pull/231
