### ISSUE TITLE
Candidate Release Comments (Reviews)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-evolution#183]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Reviews**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Reviews.md

Release candidate: https://chaoss.community/metric-reviews

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by foundjem** [comment]
looks good to me

**Comment by germonprez** [comment]
Me too
