### ISSUE TITLE
Candidate Release Comments (Issues New)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-evolution#186]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Issues New**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Issues_New.md

Release candidate: https://chaoss.community/metric-issues

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by foundjem** [comment]
Can we add severity to this metric? For example, critical etc.

**Comment by jgbarah** [comment]
What do you mean? The metric is intended to know how many issues are opened (filled) during a certain period. In this context, what do you mean by "add severity to this metric"?

**Comment by germonprez** [comment]
I think severity is not needed in this case. It could be something to consider with tags on issues but perhaps it's not necessary to accommodate right now.

**Comment by foundjem** [comment]
Ok, sounds good to me

**Comment by sgoggins** [comment]
Addresssed all the issues.
