### ISSUE TITLE
Candidate Release Comments (Issues Active)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-evolution#187]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Issues Active**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Issues_Active.md

Release candidate: https://chaoss.community/metric-issues-active

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by klumb** [comment]
Dead link (Issues are defined as in [Issues](Issues.md).) at line 8. 

Not sure if this should go to "Issues New"

 if so will need an absolute URL path

**Comment by jgbarah** [comment]
Yes, it is Issues New.

**Comment by foundjem** [comment]
Active issues: we mean from open date to closed date right?

**Comment by jgbarah** [comment]
I'm not sure what you are referring to. From the [Issues Active definition](https://github.com/chaoss/wg-evolution/blob/master/metrics/Issues_Active.md): "Issues related to the source code that showed some activity during a certain period".

**Comment by germonprez** [comment]
Addressed.
