### ISSUE TITLE
[GSoC] Proposal to add travis CI feature to reference implementations

### ISSUE THREAD

**Issue by Polaris000** [chaoss/wg-evolution#225]
The purpose of this issue is to discuss the idea and implementation for adding travis integration to the repository.

**Comment by valeriocos** [comment]
Thank you @Polaris000 to open this issue, I have just pinged @germonprez to get write access on this repo.

**Comment by GeorgLink** [comment]
I could give @valeriocos access on the grounds that he is a very active and trusted GSoC mentor. 

@sgoggins and @jgbarah, as the maintainers for the Evolution WG, are you okay with Valerio getting access to this repo?

**Comment by GeorgLink** [comment]
Update: @valeriocos already has Write permission on the repo.

**Comment by sgoggins** [comment]
Could we hear a little more about the expected use case?

**Comment by valeriocos** [comment]
Sure @sgoggins , the idea of adding CI support for the work done in GSoC came out https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/july_16_week6.txt.

Tests and CI can be useful to be sure that the outcome of the metrics implementations are correct. I guess @jgbarah can give more details about it.

**Comment by GeorgLink** [comment]
I upgraded @valeriocos to admin rights on this repo, to enable him. I still think that there is more to be discussed during the next call and maybe some innovation for all CHAOSS WGs

**Comment by valeriocos** [comment]
Thank you for upgrading my permissions @GeorgLink . I guess we can freeze everything until the next call. This shouldn't be a blocker since @Polaris000 can run the tests locally.
@Polaris000 feel free to join the discussion.

**Comment by Polaris000** [comment]
Thanks @GeorgLink. I agree with @valeriocos that this can be put on hold till the next call and when Jesus will return.

**Comment by sgoggins** [comment]
I think we can implement Travis-CI, but before we do, a group of at least two individuals who are willing to manage and maintain and setup that infrastructure on an ongoing basis should be identified.

**Comment by jgbarah** [comment]
Well, I think we're done with all of this. So, closing it.
