### ISSUE TITLE
Code_Changes Ambiguity

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#233]
After several readings its not completely clear to me if the metric `Code_Changes` should be counting "changes" as "commits" or as "files changed". I can read parts of the definition either way. 

Can we clarify our intention?

**Comment by foundjem** [comment]
In agree with you @sgoggins, there is some ambiguity in the text. On commit can change multiple files, however, for every file changed there must be a commit. So, it's like a one-many vs one-one relationship dependent on how we look at it. 

I suggest we count code_change at the atomic level as source code changes at file(s) level.

Signed-off-by: Armstrong <foundjem@ieee.org>

**Comment by jgbarah** [comment]
The idea of a commit in git (which is what we're trying to mimic with Code_Changes) is present (to my knowledge) in all modern source code management systems, and is "a change to the source code that makes sense as a single unit to the developers". Usually, it touches several files, and that's the usual metric that is present in most toolings when they consider "units of change to the source code". They are "atomic" in the sense that the developer thought that all the files should be touched together, or none at all (for example, a part of the commit may change the name of a function, and the rest are changes to files that use that function, just changing its name in them).

Of course we could also count each change to each file as the unit, or even each change to a line. But I think that would be overkill (for example, AFAIK, there is no way of getting that data via the GitHub API, at least not directly). 

WRT the current text, I'd be happy of have better redactions. Right now, the text that tries to clarify this is right in the description of the metric:

> For "change" we consider what developers consider an atomic change to their code. In other words, a change is some change to the source code which usually is accepted and merged as a whole, and if needed, reverted as a whole too. For example, in the case of git, each "change" corresponds to a "commit", or, to be more precise, "code change" corresponds to the part of a commit which touches files considered as source code.

If you can think of a better way of expressing it, please go ahead, and either submit a pull request, or propose here a better wording.

**Comment by sgoggins** [comment]
This is now under active discussion again, and will include commits in the change.
