### ISSUE TITLE
General Issues for copy editing and standardization

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#234]
remove underscores from all titles 
-code changes (complete)
- code change lines (complete)
-reviews (NA)
-reviews accepted (complete)
-reviews declined (complete)

copy edit bullet points for a standard look 
- code changes (complete)
-code change lines (complete)
-reviews (complete)
-reviews accepted (complete)
-reviews declined (complete)

**Comment by klumb** [comment]
-issues new (complete)
-issues active (complete)
-issues closed (complete)
-reviews duration (complete)

**Comment by klumb** [comment]
To be clear, these changes were made by Matt and myself.

I created the issue for transparency purposes.

**Comment by germonprez** [comment]
Complete
