### ISSUE TITLE
Update Metrics to New Template

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-evolution#253]
@ccarterlandis are you handling this? I wasn't at the last meeting so I'm not sure what the current path is to get this done.

**Comment by ccarterlandis** [comment]
Yes, I will get started on it ASAP! My current plan is to do one focus area at a time.

**Comment by germonprez** [comment]
Great. I'm happy to help.

**Comment by GeorgLink** [comment]
I think this issue is complete for v2 release. Closing.
