### ISSUE TITLE
Consolidate two template folder

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-evolution#255]
This WG has two template folders that duplicate information and are out of sync:

1. https://github.com/chaoss/wg-evolution/tree/master/focus_areas/templates
2. https://github.com/chaoss/wg-evolution/tree/master/metrics/template_folder

This issue proposes to consolidate the template folders.

**Comment by germonprez** [comment]
Agreed. We should just have one template folder with one template.

**Comment by GeorgLink** [comment]
resolved with #258
