### ISSUE TITLE
Release Candidate Comments (Code Changes)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#280]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Code Changes**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Code_Changes.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by xaviier12** [comment]
Hello everyone,

For this release, I agree about the existing, but I think we could use the message of commits.
For me, this message can contain some important information to analysis the Code Changes into a project.

If in a project, a certain structure is defined to write the message for the commits, then we would have the possibility to classify the commits.
For example, in [Odoo](https://github.com/odoo/odoo/), they have a guideline to write the message of theirs commits. They use a system of tags to know if the commit is :

- [ADD] for adding new modules;
- [IMP] for improvements;
- [FIX] for bug fixes;
- and so on...

I put the link of this [guideline](https://www.odoo.com/documentation/13.0/reference/guidelines.html#git).

Thus, I think we can use this information to know how much code changes have in this differents categories and compare the result in the differents categories on a certain period.

I've already done this condition to search a substring into the message of commits and I have made the example for this metric and the one about Code Changes Lines.

I've created a pull request about this for this metric here : #299 and another pull request about Code Changes Lines metric #300

If you are agree, I will add the implementation.

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by germonprez** [comment]
Augur provides this metric both as Code Changes and as Code Changes Lines. Both metrics are available in both the repo and the repo_group metric forms - more on that in the Augur documentation.

The links in this line are leading to some 403 errors

**Comment by klumb** [comment]
Is this metric ready to go?

**Comment by klumb** [comment]
I am marking this as ready for release and closing. Please reopen if that is not the case.
