### ISSUE TITLE
Release Candidate Comments (Code Changes Lines)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#281]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Code Changes Lines**

GitHub location: https://github.com/chaoss/wg-evolution/blob/main/metrics/Code_Changes_Lines.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by ccarterlandis** [comment]
Fixed in #302

**Comment by klumb** [comment]
I am marking this as ready for release and closing. Please reopen if that is not the case.

**Comment by foundjem** [comment]
LGTM

Code Changes Lines (Churn)

Some suggestions, under **parameter** I think the values for parameters should be bold or italicized to make them different from the other text in that line.


For example, 
<**parameter**, --description>

**Period of time** -- Start and finish date of the period. Default: forever.
The period during which changes are considered.
**Criteria for source code** -- Algorithm. Default: all files are source code.
If we are focused on source code, we need a criterion for deciding whether a file is a part of the source code or not.
**Type of source code change**.
 -- Lines added
 -- Lines removed
 -- Whitespace

Signed-off-by: Armstrong <foundjem@ieee.org>

**Comment by GeorgLink** [comment]
@foundjem did you already open a pull request? We are preparing the metrics not for release, so any changes you submit via pull request in the next half hour, we can include in the release.

**Comment by klumb** [comment]
I am marking this as ready for release and closing. Please reopen if that is not the case.

**Comment by ElizabethN** [comment]
This metric should be reviewed. 
[This recent PR](https://github.com/chaoss/wg-evolution/pull/446) only adds the Data Ethics paragraph, and fixes links to a changing metric (Code Changes Commits).
