### ISSUE TITLE
Release Candidate Comments (Reviews Accepted)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#282]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Reviews Accepted**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Reviews_Accepted.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by germonprez** [comment]
Un-bold "Question"

**Comment by ccarterlandis** [comment]
@germonprez fixed by #303

**Comment by foundjem** [comment]
LGTM

Some minor suggestions:
 - Add references
 - There is a duplicate entry for 
 **Mandatory parameters:**
>  Heuristic for detecting accepted pull requests not accepted via the web interface. Default: None.

Signed-off-by: Armstrong Foundjem<foundjem@ieee.org>

**Comment by klumb** [comment]
Is this ready for release?

@foundjem do you have specific edits in mind?

**Comment by ccarterlandis** [comment]
Barring any specific edits @foundjem may have in mind, I would say it's ready!

**Comment by foundjem** [comment]
My only suggestion was the duplicate entry for Mandatory parameters, else I am good.

**Comment by klumb** [comment]
I believe the mandatory parameters are for the specific platforms. If there is a possibility that the parameters are different for GitHub, GitLab, and Gerrit then I think we need to keep them. @ccarterlandis, what are your thoughts?

**Comment by klumb** [comment]
I am marking this for release. If we need to address unresolved comments, we can do so in the next release.

**Comment by klumb** [comment]
Changed mandatory parameters heading style

**Comment by klumb** [comment]
I am marking this as ready for release and closing. Please reopen if that is not the case.
