### ISSUE TITLE
Release Candidate Comments (Reviews Declined)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#283]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Reviews Declined**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Reviews_Declined.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by germonprez** [comment]
Un-bold "Question"

**Comment by ccarterlandis** [comment]
@germonprez fixed by #304

**Comment by foundjem** [comment]
I have a concern about this metric. For example, (i) reviews that authors themselves abandon; this will not also be merged in the codebase, similarly, (ii) declined can also mean that the author(s) did not satisfy the reviewers' requirements before they could accept and merge the patch, etc.  

Signed-off-by: Armstrong Foundjem <foundjem@ieee.org>

**Comment by ccarterlandis** [comment]
Link to Grimoirelab documentation added by #318

**Comment by klumb** [comment]
Is this metric ready for release?

@foundjem do you have specific edits in mind?

**Comment by ccarterlandis** [comment]
Barring any specific edits @foundjem may have in mind, I would say it's ready!

**Comment by klumb** [comment]
I am marking this for release. If we need to address unresolved comments, we can do so in the next release.
