### ISSUE TITLE
Release Candidate Comments (Reviews Duration)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#284]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Reviews Duration

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Reviews_Duration.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by ccarterlandis** [comment]
@germonprez fixed by #305

**Comment by klumb** [comment]
I am marking this issue as ready for release and closing. Please reopen if that is not the case.
