### ISSUE TITLE
Release Candidate Comments (Reviews)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#285]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Reviews**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Reviews.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by ccarterlandis** [comment]
@germonprez fixed in #306

**Comment by foundjem** [comment]
I think we should add some reference(s) either from Gerrit or Gitlab to support the rationale of this metric, at present, there is no reference. 

Signed-off-by: Armstrong Foundjem <foundjem@ieee.org>

**Comment by klumb** [comment]
Is this metric ready for release?

**Comment by ccarterlandis** [comment]
Barring any specific edits @foundjem may have in mind, I would say it's ready!

**Comment by klumb** [comment]
I am marking this for release. If we need to address unresolved comments, we can do so in the next release.
