### ISSUE TITLE
Release Candidate Comments (Issues New)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#286]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Issues New**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Issues_New.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by germonprez** [comment]
Remove from the Description: The first few sentences should match the description in the metrics list.

**Comment by ccarterlandis** [comment]
@germonprez fixed in #307

**Comment by foundjem** [comment]
- LGTM

We just need to add references (links to some of the metrics)

Signed-off-by: Armstrong Foundjem <foundjem@ieee.org>

**Comment by klumb** [comment]
Is this metric ready for release?

**Comment by ccarterlandis** [comment]
Barring any specific edits @foundjem may have in mind, I would say it's ready!

**Comment by klumb** [comment]
I am marking this for release. If we need to address unresolved comments, we can do so the next release.

**Comment by ElizabethN** [comment]
This metric could use a review. There is no section about Tools, nor a mention of Augur/GrimoireLab anywhere. Also, this is one of our more heavily referenced metrics so we probably want to make sure it's up to snuff.
