### ISSUE TITLE
Release Candidate Comments (Issue Age)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#289]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Issue Age**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Issue_Age.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by germonprez** [comment]
Do you want to provide a link to the New Issue metric as a pointer for describing what an Issue is? 

https://github.com/chaoss/wg-evolution/blob/master/metrics/Issues_New.md

I ask because you do this in Issue Active and Issue Closed

**Comment by ccarterlandis** [comment]
@germonprez fixed in #310

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
