### ISSUE TITLE
Release Candidate Comments (Issue Response Time)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#290]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Issue Response Time**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Issue_Response_Time.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
Provide a Link to GrimoireLab in the Tools Providing the Metric.

**Comment by germonprez** [comment]
Do you want to provide a link to the New Issue metric as a pointer for describing what an Issue is?

https://github.com/chaoss/wg-evolution/blob/master/metrics/Issues_New.md

I ask because you do this in Issue Active and Issue Closed

**Comment by ccarterlandis** [comment]
@GeorgLink any thoughts on what link should we use for GrimoireLab under the "Tools Providing the Metric" section?

**Comment by GeorgLink** [comment]
Depending on what the goal is:

1. The generic GrimoireLab homepage that we often link to: https://chaoss.github.io/grimoirelab/
2. The panel: https://chaoss.github.io/grimoirelab-sigils/panels/github-issues-efficiency/

**Comment by foundjem** [comment]
In addition, on 

> Tools Providing the Metric, 
we should mention that Selected Tools providing the Metric. So that we are not locked down by these two tools.

Signed-off-by: Armstrong Foundjem <foundjem@ieee.org>

**Comment by ccarterlandis** [comment]
Link to Grimoirelab documentation added by #318

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.

**Comment by klumb** [comment]
Sorry reopened as it is connect to PR #321

**Comment by klumb** [comment]
@carter, do you think we are good here?

**Comment by ccarterlandis** [comment]
Yes! @klumb

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.

**Comment by ElizabethN** [comment]
This metric is a filter on another metric ([Time to First Response](https://github.com/chaoss/wg-common/blob/main/focus-areas/time/time-to-first-response.md)). Should it exist on its own? Might be good to review this metric.

**Comment by ElizabethN** [comment]
Closing this, as I think this issue has been resolved.
