### ISSUE TITLE
Release Candidate Comments (Issue Resolution Duration)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#291]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Issue Resolution Duration**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Issue_Resolution_Duration.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by foundjem** [comment]
LGTM!

Signed-off-by: Foundjem <foundjem@ieee.org>

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by ccarterlandis** [comment]
@germonprez fixed in #311

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
