### ISSUE TITLE
Adjust the weekly meeting time

### ISSUE THREAD

**Issue by JerryKuan** [chaoss/wg-evolution#333]
I notice that the group meeting time is every other Wednesday at 12:00 pm CDT.  But for other parts of the world, this time may be the rest time in the evening. for example, China is at 1 am, which is 13 hours away from the US.  Because of this, many developers in China may not be convenient to attend.

**Comment by GeorgLink** [comment]
Thanks @JerryKuan, 

What would be a good time? Do you know of people who would join the calls if we changed the time?

We are open to adjusting the meeting time when it means we can accommodate more people. In the past our efforts to have times that are more suitable for China have not led to more participation and so we switched back to times more convenient for the people who regularly join the call. This is just to give you some background and to encourage the conversation about the timing of our meetings.

We are also discussing having a meeting convenient for people in Asia Pacific: https://github.com/chaoss/wg-risk/issues/92

**Comment by JerryKuan** [comment]
Hi @GeorgLink , Thanks for your response.  As a matter of fact, there are 6 people in our lab interested  in CHAOSS, and we want to involve in it. Last week, we have started to follow up with 3 WGs including common, diversity and evolution. Another student and I want to follow up on this. I think two hours ahead of time may be much better, which the US is at 9 am, and China is at 10 pm. If it is not convenient for you, I think it's ok from 8:30 am to 10:30 pm in China time. The above is just my personal suggestion.

**Comment by GeorgLink** [comment]
That's great. I'm adding @germonprez to the conversation, because he has been leading the conversation around how we can accommodate meeting times for people in China's time zone.

**Comment by germonprez** [comment]
Hi @JerryKuan 

We are having our first meeting for the Asia-Pacific region on April 8, 2020 at 9am US Central Time. The connection details are at: 

https://unomaha.zoom.us/j/508234161?pwd=Uy9hTm9qSEY4T3poMzczdEQ1dFZSUT09

Meeting ID: 508 234 161
Password: CHAOSS

Please feel free to drop in.

**Comment by GeorgLink** [comment]
Thanks Matt!

**Comment by JerryKuan** [comment]
Thanks a lot, @germonprez @GeorgLink. I look forward to participating.

**Comment by sgoggins** [comment]
We meet at 9am CDT.
