### ISSUE TITLE
Change to Released Metric "Reviews": Adding Two New Filters

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#337]
This issue was created to capture the continuous release notes. Insight from comments will be used to create the regular release note.

Pull Request #332  has two new filters added to the "Reviews" metric, which is released. The filters are : 
1. Review Opened
2. Review Closed

**Comment by klumb** [comment]
Is this a metric that is in the comment period?

**Comment by sgoggins** [comment]
Adding two filters to the Reviews: New Metric Release for "Review Status: Open or Closed.  Update to existing metric: Reviews.

**Comment by foundjem** [comment]
I have one concern here if the "continuous release notes" depends on comments. What if there is no best practice to write precise and concise commit messages? For example, some ecosystem/project enforces the commit message best practice.

Signed-off-by: Armstrong <foundjem@ieee.org>

**Comment by klumb** [comment]
@sgoggins 
Is this metric ready?

**Comment by sgoggins** [comment]
@klumb : Yes.
