### ISSUE TITLE
Evolution Continous Release Notes

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#353]
This issue was created to capture the continuous release notes. Insight from comments will be used to create the regular release note.

Please coordinate Release using the release spreadsheet:
https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=700620500

Please add comments to this issue for each new metric.
Example comments could be:

    name of new metric and date of release
    descriptions of changes to existing metric
    Changes to focus areas or restructuring of WG

**Comment by klumb** [comment]
**New Metric**
New Contributors
https://github.com/chaoss/wg-common/blob/master/focus-areas/what/types-of-contributions.md
Comment Period Issue #329 
Releasing to website ... Date ??? (kl will edit)

**Comment by ccarterlandis** [comment]
@klumb thanks Kevin! The New Contributors metric is ready for release on the website now. 😄

**Comment by foundjem** [comment]
Are these #353, #329 still open? 

Signed-off-by: Armstrong<foundjem@ieee.org>

**Comment by klumb** [comment]
@Armstrong, this issue (#353) will stay open to collect release notes for the next regular release (all metrics released). #329 was the comment period issue for the new contributors metric. It is closed because the comment period ended.

**Comment by foundjem** [comment]
@klumb  OK Thanks!

Signed-off-by: Armstrong <foundjem@ieee.org>

**Comment by sgoggins** [comment]
**NOT** for continuous release, but next full metrics release: 
1. Update to the "Reviews" Metric to include new filters. Specifically, Adding two filters to the Reviews: New Metric Release for "Review Status: Open or Closed. Update to existing metric: Reviews.

The comment period issue is here: https://github.com/chaoss/wg-evolution/issues/337

**Comment by klumb** [comment]
New Metric
Inactive Contributors
https://github.com/chaoss/wg-evolution/blob/master/metrics/Inactive_Contributers.md
Comment Period Issue #357

**Comment by sgoggins** [comment]
@klumb ... this was released under the continuous release  process.  It looks like I missed the two filters comment I made for metrics release, so I will add them now.

**Comment by sgoggins** [comment]
@klumb : The reviews filter updates were already there, so I just edited out the review period text at the top of this metric.

**Comment by klumb** [comment]
closing for release 2020-08
