### ISSUE TITLE
Rethinking Folders in WG-EVOLUTION Repo

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#356]
Do we need the following folders any longer: 
1. implementations
2. use_cases
3. bin

Do we need the Evolution meeting notes in markdown any longer? All the other working groups are just using the google docs. 

This arises from discussion during May 6, 2020 meeting.

**Comment by sgoggins** [comment]
The CHAOSS philosophy on clarity of communication is "Less is More".

**Comment by sgoggins** [comment]
(This philosophy has evolved over the past six months).

**Comment by ccarterlandis** [comment]
Yes, we need the meeting notes. Google Docs is not universally accessible (e.g. it's banned in China, Sudan, Syria, many Arab countries, etc) and for potential contributors living in areas where Google is not accessible, having the meeting notes uploaded to the repo is the only they would ever be able to access them without using a VPN or proxy of some sort. 

This is in my humble opinion far too high of a barrier to entry for getting involved with CHAOSS. It's for this reason that I think we should not be using Google Docs in the first place, but that's neither here nor there and is a decision out of my control.

I think the other 3 folders can go, less is indeed more and I fear including sample implementations could give the impression that we have preconceived notions about how a metric should be implemented, which we don't. The fewer things to maintain, the better!

**Comment by ccarterlandis** [comment]
I believe all these folders were removed some time ago. Closing this issue, since it's been addressed
