### ISSUE TITLE
Not sure if this metric is a candidate for changing Reviews to Change Requests

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-evolution#372]
https://github.com/chaoss/wg-evolution/blob/master/metrics/New_Contributors_Code_Reviews.md

**Comment by ccarterlandis** [comment]
We went ahead and decided to change the metric title to "New Contributors Change Requests", in order to keep language consistent. Metric: https://github.com/chaoss/wg-evolution/blob/master/metrics/New_Contributors_Change_Requests.md
