### ISSUE TITLE
Why are my PRs triggering errors in Travis

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-evolution#376]
@sgoggins why are my PRs to update the metrics in this WG not passing Travis checks?

**Comment by sgoggins** [comment]
@germonprez : Its not you. There must be some jupyter notebooks remaining after we did some cleanup. I'll check.

**Comment by sgoggins** [comment]
@germonprez : I deleted the webhook for travis-ci, as we are no longer building software examples, and the integration was significantly out of date. 

You can *ignore* the Travis-CI errors. New PRs should not have them.

**Comment by germonprez** [comment]
@sgoggins do I need to reissue these PRs?

**Comment by sduenas** [comment]
@germonprez do you have access to this repo in Travis: https://travis-ci.org/github/chaoss/wg-evolution? can you manage it? I found that I don't have access anymore to all the grimoirelab repositories on https://travis-ci.org/ anymore.

**Comment by germonprez** [comment]
Thanks @sduenas. I think that @sgoggins has sorted this out. 

I still don't know if I have to reissue the PRs :)
