### ISSUE TITLE
Release/Change_Request_Acceptance_Ratio.md

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#392]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Change_Request_Acceptance_Ratio.md

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Change_Request_Acceptance_Ratio.md

See all release candidates: https://chaoss.community/metrics/

**Comment by klumb** [comment]
closing for release
