### ISSUE TITLE
Standardize working groups repositoryoy structure

### ISSUE THREAD

**Issue by friyaz** [chaoss/wg-evolution#395]
Hello everyone,

We are trying to make a standard and uniform repository structure for all working groups of CHAOSS. This will make things easier for new members. See this [document](https://docs.google.com/document/d/1chPzgJa49sO_f3wVqp_NLJupSVyKHSVyuFuwzl4m4KI/edit#) to know details about the proposed repo structure.

Please provide your feedback or concern about this proposal.

**Comment by sgoggins** [comment]
This is currently being worked on at the CHAOSS community level. There will be separate folders for completed metrics. Incomplete, unreleased metrics will only be in Google Documents.  These documents can be found in this spreadsheet: https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=1004270137
