### ISSUE TITLE
These may be errors of the metric 'Issue Closed'

### ISSUE THREAD

**Issue by xiaoya-Esther** [chaoss/wg-evolution#400]
When reviewing translations of the metric **Issue Closed**, here is what I found that confused me. Are the phrases "active issues" in black circles actually refer to "closed issues"?

![image](https://user-images.githubusercontent.com/56542972/112464029-f3869f00-8d9d-11eb-9bf2-6067cad47484.png)

**Comment by sgoggins** [comment]
fixed in pull request #404

**Comment by ElizabethN** [comment]
Thanks for catching this @xiaoya-Esther!
