### ISSUE TITLE
Different folder for 'completed' and 'under development' metrics

### ISSUE THREAD

**Issue by yash2002109** [chaoss/wg-evolution#402]
Hi Everyone,

I was working on classifying the metrics into their respective focus areas (#395). While classifying I noticed that in the [metrics](https://github.com/chaoss/wg-evolution/tree/master/metrics) folder a lot of metrics seem to be in the stage of development. . So I was thinking of doing the following changes.

- Move the developed metrics to a new 'focus-areas' folder.
- The ones in the stage of development can be kept in the metrics folder itself

There is another similarly named folder '[focus_areas](https://github.com/chaoss/wg-evolution/tree/master/focus_areas)', which contains the tables of metrics classified as per their focus areas. I was thinking of utilizing those files as the README.md for each focus area in the new 'focus-area' folder.

Please let me know your thoughts and suggestions on this.

**Comment by sgoggins** [comment]
The CHAOSS Community decided that we will remove metrics under development from the repository, and and link them to this spreadsheet, which contains links to google docs where the metrics are under development: https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=1004270137
