### ISSUE TITLE
Add new matrics for labels/tags associated with issue/PR

### ISSUE THREAD

**Issue by li-clement** [chaoss/wg-evolution#403]
When we respond to an issue or review a PR, we usually hope that the Issue/PR is clearly classified and described in detail. Many communities use labels/tags system for issue/PR classification. The labels/tags associated with an issue affect the developer's understanding of the Issues/PR and the time of feedback. So I think we can have some metrics for labels/tags

- How many labels/tags are attached to the Issues/PR?

- How many types of labels/tags are attached to the Issues/PR?

Meanwhile, the metric **Time to First Response** takes **attention** into consideration ( I don't know if **attention** means a comment to an issue/PR ). Sometimes, contributors who do not want to response in words, thay give labels to issue/PR to help others to solve the problem, I think that is also a way to make contribution.

I think **Time to First Response** can also take labels into account, so we can say:

- how fast a label is attached to a Issues/PR

Thanks!

**Comment by robekeane** [comment]
> We have recorded this as an issue being considered. Good idea!!, @robekeane ! (Code Development Process Quality) https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=1004270137

Thanks, @sgoggins

**Comment by ElizabethN** [comment]
Going to close this issue since this work is happening elsewhere.
