### ISSUE TITLE
Reorganize Repository According to CHAOSS Standard

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#405]
https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=1004270137

**Comment by GeorgLink** [comment]
Next: remove `focus_areas` and `metrics` folders from the root of the repo.

**Comment by yash2002109** [comment]
@GeorgLink, Should I submit the required PR for this?

**Comment by GeorgLink** [comment]
Yes, a PR would be great!

**Comment by yash2002109** [comment]
I see many metric files in the `metrics` folder that are not listed in the spreadsheet. I hope it's okay to delete those files..?

**Comment by klumb** [comment]
@yash2002109 

Yes, you can delete them.

**Comment by yash2002109** [comment]
Also, I noticed that there is `standard-readme` badge for the [README](https://github.com/chaoss/wg-evolution/blob/master/README.md) file of this working group. I was wondering if we could incorporate the badge in README files of other working groups too?

**Comment by klumb** [comment]
This still needs to be done

https://github.com/chaoss/governance/blob/master/templates/WG-README.md
