### ISSUE TITLE
Release Candidate / Contribution Attribution

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#410]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Contribution Attribution**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/focus-areas/community-growth/contribution-attribution.md

See all release candidates: https://chaoss.community/metrics/

## CHAOSS Metric Quality Checklist
This checklist is used for new and updated metrics to ensure we follow CHAOSS quality standards and processes. Below checklist items don’t have to be completed all at once: create the metric release candidate issue first and then start working on the checklist.

### Process

- [x] Create the “review issue” in the authoring WG’s repo for comments during review period and paste this template in
- [x] Create pull request to edit or add metric to WG’s repo (after checking Content Quality and Technical Requirements below)
- [x] Add the new metric or metric edit to release notes issue in working group repo
- [x] Update the [Metrics Spreadsheet](https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit)
- [x] Create issue in [CHAOSS/Translations repository](https://github.com/chaoss/translations) to kick-off translation to other languages (please use the the translation issue template)
- [x] "Metric Candidate Release" label added to the metric release candidate issue.
- [x] Metric was added to website

**When above steps are completed:**

- [x] Announce new/updated metric on mailing list, newsletter, community Zoom call, and Twitter. This can be coordinated with the community manager.

### Content Quality

- [x] Required headings are filled in, including Questions.
- [x] Description provides context to metric
- [x] Objectives list sample uses for the metric and desired outcomes
- [x] If any, DEI uses of the metric are included Objectives
- [x] Optional headings that have no content were removed
- [x] Contributors section lists those contributors that want to be named
- [x] The name of the metric is the same in (1) metric heading, (2) metric file name, (3) focus area, (4) metrics spreadsheet, (5) “review issue”, (6) translation issue, and (7) website

### Technical Requirements

- [x] Message in the metric markdown file that the metric will be part of the next regular release is at top of page and the links are correct (this is in the [metric template](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md))
- [x] Metric file name is the full metric name and only contains lower case letters and hyphens (“-”) for spaces
- [x] Images are included using markdown and relative links (as described in the metrics template)
- [x] Images have at least one empty line above and below them
- [x] Ensure images are placed in image folder and followed [naming convention](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md)
- [x] If new focus area is created, ensure focus area is added to wg repo readme and focus area folder readme
- [x] Within the focus area, add the metric in the table and provide the link to the metric and metric question
- [x] Ensure tables within metric are converted as image and placed in the image folder (both original MD and screenshotted PNG format) and follow the naming convention
- [x] No HTML code in the metrics markdown file

**Comment by foundjem** [comment]
@klumb the GitHub link seems broken, please check  :)

Signed-of-by: Armstrong <foundjem@ieee.org>

**Comment by mtift** [comment]
@klumb Should the URL above be https://github.com/chaoss/wg-evolution/blob/master/focus-areas/community-growth/contribution-attribution.md or should we, in fact, be adding a new directory called `metrics`?

**Comment by klumb** [comment]
Sorry, I pulled this from a previous release - We have changed the file structure since then.

@mtift the link should be correct now. We want to put it in the community growth focus area

@foundjem, we created the issue before the PR was in so we could include the disclaimer at the top. The link should be good now, however, there wont be anything there until the PR is done.

**Comment by mtift** [comment]
For what it's worth, here's the PR: https://github.com/chaoss/wg-evolution/pull/411

**Comment by GeorgLink** [comment]
For the visualizations, can we get a figure title that describes it and where the screenshot was taken from?

**Comment by sgoggins** [comment]
This metric possibly also related to the *Contributors* (Common Working Group), and *Elephant Factor* (Risk Working Group)

**Comment by lucasgonze** [comment]
I made trivial copy edits without going through issue first, on the assumption that this would be preferred.

This text is hard to understand: "Question: Who has contributed to an open source project and what attribution information about people and organizations is assigned for a contribution?"

I propose: "Question: which people and organizations should get attribution?"

**Comment by sgoggins** [comment]
@lucasgonze : You mention making some copy edits. Could you direct us toward where we might find those? We looked for a pull request and did not see one. 

We think somewhere between your question and the existing one is probably going to be the most clear and contextualized. @mtift : What do you think?

**Comment by mtift** [comment]
While I agree there might be room for improvement, I think the question as it exists now captures the intent well. This metric is about more than just **who** ("which people and organizations"), it's also about **what** sorts of activities (i.e. "attribution information") can or should count as a contribution (code, organizing, attending meetings, etc.).

**Comment by lucasgonze** [comment]
> @lucasgonze : You mention making some copy edits. Could you direct us toward where we might find those? We looked for a pull request and did not see one.

I also looked for git history referencing the change and didn't find it. I also looked in my activity log and saw nothing. I must have failed to commit.

**Comment by klumb** [comment]
I am closing this for the release.

I think that there are a few issues we can address when we audit all of the evolution metrics during the next release.

namely, links to known metrics and clear language.
