### ISSUE TITLE
New Metric Idea: Issue Triaging 

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-evolution#432]
This proposed new metric comes from the Metrics Model working group: 
    https://gist.github.com/lucasgonze/4a0319b02e11e01334b7694d2e7fc072  

We suggest that you build this metric for us!

**Comment by klumb** [comment]
What does a issue triaging metric measure?

**Comment by germonprez** [comment]
Pinging @lucasgonze for some insight :)

**Comment by lucasgonze** [comment]
This is to measure the number of people doing program management work involving tickets, something that is a big part of my own career.

* Identifying and closing dups
* Noticing worthy items that have fallen in the cracks
* Rewriting unclear descriptions
* Breaking up multipart tickets into multiple tickets
* Adding labels and organizing in boards

A quantitative sign of the above is editing a ticket you didn't create. If somebody does this once they may just be a drive-by commenter. If somebody does this more than three times chances are low they aren't doing project management.
