### ISSUE TITLE
New Metrics to Develop from the Metrics Model WG

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-evolution#458]
Hi, 

This is a list of metrics that need to be developed to be available for a few of the metrics models: 

1.	Issues Updated -- Issues updated are those that updated during a certain period.
2.	Issue Comments -- Projects discuss how they are fixing bugs or adding new features in an issue tracking system. Each of these issues are opened by a certain person and are later commented and annotated by many others.
3.	✅ Number of Downloads -- Determine the number of downloads of software artifacts per week and determine the number of hosts downloading software artifacts per week.
4.	CI Test -- determine if the most recent (~30) commits contain CI tests
5.	CI Build Time -- CI build time triggered by code commit
6.	:eyes: Ratio of Issues to Change Requests -- Percentage of PRs linked to issues
7.	Change Request Age – Average age of open change requests 
8.	Change Request Processing Time -- Average/Median processing time (days) for change requests in the last 90 days, including closed/accepted change request and unresolved change requests.

**Comment by foundjem** [comment]
Hello @germonprez,
Sure, we will develop these metrics. I think we also have two or more pending; I will have to double-check with @sgoggins. 

Signed-off-by: Foundjem<foundjem@ieee.org>

**Comment by germonprez** [comment]
Thanks!

**Comment by sgoggins** [comment]
I think items 1, 2, 3, 7, & 8 are more urgently needed than 4, 5, & 6

**Comment by sgoggins** [comment]
Items 7 & 8 are filters on the Change Requests metric.

**Comment by ElizabethN** [comment]
Ratio of issues to Change Requests is being developed here https://docs.google.com/document/d/1uD_2dOmuaakwq5-frV8Pgg9Yf4p_P-vCrvnaDnP55B0/edit#heading=h.z40ienlhtj66

**Comment by ElizabethN** [comment]
Item 3 (Number of Downloads) has been released here: https://github.com/chaoss/wg-evolution/blob/main/focus-areas/community-growth/number-of-downloads.md :tada:

**Comment by sgoggins** [comment]
I made a few edits to clarify the definition. I think the name is “Ratio…”

From: Elizabeth Barron ***@***.***>
Date: Tuesday, November 15, 2022 at 10:17 AM
To: chaoss/wg-evolution ***@***.***>
Cc: Sean P. Goggins ***@***.***>, Mention ***@***.***>
Subject: Re: [chaoss/wg-evolution] New Metrics to Develop from the Metrics Model WG (Issue #458)

Ratio of issues to Change Requests is being developed here https://docs.google.com/document/d/1uD_2dOmuaakwq5-frV8Pgg9Yf4p_P-vCrvnaDnP55B0/edit#heading=h.z40ienlhtj66

**Comment by ElizabethN** [comment]
@sgoggins Sorry, "released as part of the continuous release process for community review." It's not clear to me if we are continuing the official packaged releases we used to do twice a year. :blush:

**Comment by sgoggins** [comment]
Thanks for clarifying, Elizabeth!! 😃 I was pretty sure that was now the case, and wanted to ensure I understood the current process.

From: Elizabeth Barron ***@***.***>
Date: Thursday, December 1, 2022 at 12:32 PM
To: chaoss/wg-evolution ***@***.***>
Cc: Sean P. Goggins ***@***.***>, Mention ***@***.***>
Subject: Re: [chaoss/wg-evolution] New Metrics to Develop from the Metrics Model WG (Issue #458)

@sgoggins<https://github.com/sgoggins> Sorry, "released as part of the continuous release process for community review." It's not clear to me if we are continuing the official packaged releases we used to do twice a year. 😊

**Comment by ElizabethN** [comment]
I'm going to close this because I think all of these are captured and being tracked in [the spreadsheet](https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=1004270137).
