### ISSUE TITLE
Use case: Characterize a participant, both within a given project and across projects.

### ISSUE THREAD

**Issue by kfogel** [chaoss/wg-evolution#48]
This may be a long-ish description -- I'm porting a formerly private conversation with @jgbarah over to here.  (If there's some more appropriate forum, please let me know!)

To set some context: almost all the information I'd want to find out about a project is actually built up from the activity of the *people* in that project, so I've come to think that most of the metrics I'm looking for are about people primarily, and projects secondarily.

* **Use Case:** Evaluate whether a person should be offered commit access or whatever the equivalent is for the kind of work they're doing (e.g., maybe it's actually "a vote on the steering committee" or "an editorship position in the documentation" or whatever).  The point is, existing maintainers often find themselves evaluating a person's activity in order to determine whether that person should be invited into some kind of formal maintainer role.

  The metrics required to do this thoroughly are interesting:

  - The data collection system needs a concept of the person's unified identity.  I.e., this account over here in the repository (which may or may not use the same authn system as the issue tracker) is the same as that account over there in the wiki... is the same person as these two email addresses on the mailing list... all of which are the same person as so-and-so over in the chat platform, etc, etc.  (Obviously it will not always be possible to determine these correspondences automatically, so there needs to be a UI where some knowledgeable human can come in and just *tell* the system that two accounts both belong to the same person, after which the system can faithfully remember that fact.)
  - A time-based view of when the person is active.  I almost care *that* they are active more than *how* they're active.  It's hard to tell, in an automated way, whether a given commit was more of a contribution than an answer given in Zulip or IRC, for example.  But just looking at *when* and *how often* the person did stuff tells you a lot.
  - When the person is responding to someone else in a thread (whether it be in the issue tracker, mailing list, or somewhere else), what is the range of latencies of the person's responses?

So that's what I want: an ability to look at a list of participants in a project, and see what they've been up to.  Looking at a person's activity within a single project would already be useful.  Ideally, I'd like to look at that person's activity in as many projects as possible.  For example:

* **Use Case:** If I knew that a particular bug reporter had a tendency to report bugs that resulted in associated bug fixes that were successfully merged, with the ticket closed as "FIXED" (or whatever the equivalent state is in that tracker), then when that person reported a bug in my project, I might pay attention more quickly.

I'm carefully avoiding getting into project health metrics for the moment, but expect that they would largely grow out of person-based metrics.  And there are many more person-based metrics we could all think of, of course; the ones above are just a start.  The prerequisite for all person-based metrics is a unified identity tracking system, I think.

**Comment by jgbarah** [comment]
Thanks a lot, @kfogel. Yes, this is the place for having this conversation ;-)

First comment is purely procedural: in this issue, are you submitting one or two cases? If they are two, I think it is better to open one issue for each of them (we could keep this for the first use case in your description, and have a new one for the second one). If they are only one, I think I need more data to see how they come together...

Second comment is also procedural, for anyone willing to contribute. This issue is a part of the process described in the [use cases README](https://github.com/chaoss/wg-gmd/blob/master/README.md) in this repository. As such, please provide any feedback you may want about how to better describe this use case, but let's try to maintain it concrete (that is, we don't need to make it valid for any likely scenario, and therefore @kfogel, who is proposing it, can define its scope).

**Comment by jgbarah** [comment]
Now, with respect to the proposal itself, we should end up filling in this [template](https://github.com/chaoss/wg-gmd/blob/master/use_cases/template.md). So, we would need to define the main goal(s), main actor/stakeholders, and questions that metrics should help to answer. I think goals and actor/stakeholders can be easily extracted from the proposal, but we still need to find out about the specific questions that metrics should help to answer. I suggest some (but I'm not sure if they are appropriate):

* How much expert on  the project is this person?
* How much activity in the project had this person in the past?
* How valuable were the contributions of this person?
* To which extent this person has helped in the learning / engagement process of others?

**Comment by jgbarah** [comment]
Ping @kfogel! ;-)

**Comment by kfogel** [comment]
Hi, @jgbarah.  I reluctantly have come to the conclusion that it's probably two use cases, so I've opened issue #61 for the second one.

Looking at the questions you asked:

* How much expert on the project is this person?

  I think it doesn't matter for our purposes.  I'm kind of changing the use case here, or narrowing it down: I think this is more about making a first pass.  That is, we're not directly evaluating expertise here, we're just trying to figure out where to devote our attention -- that is, *whom* to evaluate.  Once we've figured that out, we can use a multitude of other techniques, archives, tools, and social navigation knowledge to do the rest of the assessment for maintainership.

* How much activity in the project had this person in the past?

  Not sure I understand this one?  This sounds like exactly the information that the use case proposes to gather as input metrics in the first place.

* How valuable were the contributions of this person?

  Similarly to the answer to the first question: maybe that doesn't matter here.  We're just figuring out whose contributions to evaluate in the first place.  Once we have determined the person, we will look more closely at their contributions.

* To which extent this person has helped in the learning / engagement process of others?

  Well, we can try to infer that from responsiveness metrics, but ultimately we'd have to look at some of the responses themselves to be sure.  Having easy access to those responses and those threads would make that process fairly easy, though -- you just dip in and pick a random sample to evaluate (that is, evaluate in a non-automated way).

**Comment by jgbarah** [comment]
> Hi, @jgbarah. I reluctantly have come to the conclusion that it's probably two use cases, so I've opened issue #61 for the second one.

OK, thanks. I will follow up there too.

**Comment by jgbarah** [comment]
WRT the questions, first a clarification. We're trying to apply GQM methodology (goal-question-metric). That's the reason why I wanted to define the questions before we enter into the metrics. I know you did your analysis already, so it may seem awkward to talk about the questions when you are proposing metrics. But the idea is to first ensure that the questions of your use case are clear, and then discuss the metrics based on how they help to answer those questions.

So, summarizing, based on your comments to the questions I proposed:

* How much expert on the project is this person? I understand that his question does not make sense to reach your goal, so let's not consider it.

* How much activity in the project had this person in the past? It seems you agree this is the fundamental question for helping to reach the goal, so let's keep it.

* How valuable were the contributions of this person? As with the first question, let's not consider it.

* To which extent this person has helped in the learning / engagement process of others? If I understand well, you prefer also not to consider it, right?

This would leave us with a single question, which is no problem at all, if you think it captures well what you need to reach the goal.

I suggest also to define the goal, based in your comments as "Get a shortlist of people who should be consdiered for being offered commit access or whatever the equivalent is for the kind of work they're doing".

If you agree with all of this, I can produce a pr based on the template, and we discuss the metrics and everything in it.

**Comment by germonprez** [comment]
@kfogel just checking if you have any comments on this. If nothing in the next few weeks, we're going to close this but happy to open it again at any time.

**Comment by jgbarah** [comment]
@kfogel ???

**Comment by jgbarah** [comment]
Finally I found the time to produce the pull request (#91). @kfogel (and everyone else), please have a look at it. Any comment / review is appreciated!

**Comment by sgoggins** [comment]
@kfogel  and @GeorgLink : Can this issue be closed with the pull request.

**Comment by sgoggins** [comment]
Closing as discussino is continuing in another issue.
