### ISSUE TITLE
Use Case: Community Managers

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#50]
Creating a use case for community managers.

**Comment by germonprez** [comment]
Should we use this issue to track all possible use case contexts?

**Comment by sgoggins** [comment]
Created a pull request to add this use case.

**Comment by vchrombie** [comment]
@jgbarah @sgoggins 
If PR #76 is completed and enough, I think we can close this issue.

**Comment by jgbarah** [comment]
Yes, I think so. Thanks for the suggestion, @vchrombie.
