### ISSUE TITLE
GSoC Idea: Implementing CHAOSS Metrics in Augur

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#82]
# Ideas for Google Summer of Code projects

### Description

[Augur](http://www.augurlabs.io) is a fully functional prototyping web stack for CHAOSS metrics that leverages cutting edge web technologies including VUE, NodeJS and Python. It provides structured data mined from git repositories using a plugin architecture that incorporate other open source metrics projects like [Facade](http://facade-oss.org/) and [FOSSology](https://www.fossology.org/). 

In this GSoC project we plan to implement Risk metrics and other metrics within the Growth-Maturity-Decline [CHAOSS metrics and use cases](https://github.com/chaoss/wg-gmd) using Augur, focusing on what we have unearthed as the open source community manager use case. The aims of the project are to: 
1. Construct core open source software metrics defined by CHAOSS and
2. Assemble filtered, comparative collections of those metrics in ways that community managers want to consume. 

The aims of the project are as follows:

  * Acquiring knowledge on Augur toolchain to generate metrics from available data sources.  
  * Creating VUE visualizations and API's to support the enumerated metrics and metric collections. 
  * Writing Python code to query Facade, Augur and other datasets. 

Right now, based on Augur prototypes and follow up discussions so far, we have the following observations that will inform our work both the “Growth Maturity and Decline” working group and in Augur Development. Here are a few things we have learned from prototyping Augur with community managers. These features in Augur are particularly valued:
1. Allowing comparisons with projects within a defined universe of of projects is essential
2. Allow community managers to add and remove repositories that they monitor from their repertories periodically
3. Downloadable graphics
4. Downloadable data (.csv or .json)
5. Availability of a “Metrics API”, limiting the amount of software infrastructure the community manager needs to maintain for themselves. This is more valued by program managers overseeing larger portfolios right now, but we think it has potential to grow as awareness of the relatively light weight of this approach becomes more apparent. By apparent, we really mean “easy to use and understand”; right now it is easy for a programmer, but less so for a community manager without this background or current interest.

With these advantages in mind, making the most of this opportunity to help community managers with useful metrics is going to include the availability of date summarized comparison metrics. These types of metrics have two “filters” or “parameters” fed into them that are more abstractly defined in the Growth, Maturity, and Decline metrics on the CHAOSS project.

1. Given a pool of repositories of interest for a community manager, rank them in ascending or descending order by a metric
2. Over a specified time period or
3. Over a specified periodicity (e.g., month) for a length of time (e.g., year).

For example, one open source program officer we talked with is interested in the following set of date summarized comparison metrics. Given a pool of repositories of interest to the program officer (dozens to hundreds of repositories):
1. What ten repositories have the most commits this year (straight commits, and lines of code)?
2. How many new projects were launched this year?
3. What are the top ten new repositories in terms of commits this year (straight commits, and lines of code)?
4. How many commits and lines of code were contributed by outside contributors this calendar year? Organizationally sponsored contributors?
5. What organizations are the top five external contributors of commits, comments, and merges?
6. What are the total number of repository watchers we have across all of our projects?
7. Which repositories have the most stars? Of the ones new this year? Of all the projects? Which projects have the most new stars this year?

Further elaboration on the community manager use case is available on the CHAOSS website: [Community Manager Metrics Use Case](https://chaoss.community/news/2018/11/16/metrics-with-greater-utility-the-community-manager-use-case/)

  * _Difficulty:_ Medium
  * _Requirements:_ Python programming. Interest in data analytics. Willingness to understand data structures and our web stack internals and CHAOSS metrics.
  * _Recommended:_ Experience : NodeJS Programming. VUE Programming.
  * _Mentors:_ Sean Goggins, Jesus M. Gonzalez-Barahona

## Microtasks

 - **Microtask 0**: Familiarize yourself with [augur](http://www.github.com/chaoss/augur) by downloading and configuring the dev branch. For a little more context about what we are trying to accomplish with Augur's prototyping, checkout the blog posts on the [Augur Website](http://www.augurlabs.io). The community manager use case is especially interesting. 
 - **Microtask 1**: Using the Augur reference database included in the setup, configure a new metric from those available an not implemented in the ["Metrics Status" page](http://dev.augurlabs.io/metrics_status).
 - **Microstask 2**: If you want, take a look at the configuration for VUE cards in the frontend/ folder for augur, google Vue, and see what kinds of new visualizations you might want to try out for some of the already existing metrics. 
 - **Microtask 3**: Make a pull request to update the newcomer documentation or, if you have questions about getting started in the steps above, open an issue in the Augur repository.

**Comment by ManuelLecaro** [comment]
Hello, I'm interested in this project and have been working on the microtasks. I would like to ask if like in the other GSoC ideas that is recommended to show the completion of some microtasks, on this project if I want to show them as well, may I create a repository and upload evidence like screenshots because there are no coding related tasks, like in this [issue](https://github.com/chaoss/grimoirelab/issues/182). 
Thanks in advance for your response

**Comment by sgoggins** [comment]
Hi @ManuelLecaro : Please submit!

**Comment by sgoggins** [comment]
@parthsharma2 contributed a pull request to augur. He communicated directly in the repository, which is my fault, not his.

**Comment by bing0n3** [comment]
Hello, I'm also interested in this project. I have contributed a few pull requests to augur, accomplished all microtasks and submitted my proposal.

**Comment by sgoggins** [comment]
OK, @bing0n3 : we will evaluate your pull request.

**Comment by jgbarah** [comment]
I think this is done by now.
