### ISSUE TITLE
Address Refining Comments in Pull Request #90

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#99]
I made some comments for refining the goals and questions under code activity in pull request #90 that mostly deal with : 
- How to count open pull requests
- How to deal with reopened issues

Both in terms of counting them within ratios and summary metrics.

**Comment by jgbarah** [comment]
Good points, @sgoggins! What about considering them in the details for the metrics (I mean, the file describing the metric) instead of at the focus area (questions, goals) level?

**Comment by jgbarah** [comment]
After #90 was merged, we still need to address these concerns. I'm leaving this issue open for not forgetting about that...

**Comment by sgoggins** [comment]
This issue will be revisited with the new metrics release.
